name: Tests
on: push
jobs:
  Linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run poe test
